### PR TITLE
Misc edits

### PR DESCRIPTION
**Pull request by williln**
cc @phildini -- I can't add you as a reviewer, maybe you need to be added to the team or the repo or something? 

I got started on an overarching "wedding-style" planning timeline, loosely broken down by area. Would love feedback! It's obviously not done but it's a start. 

I also removed "team" from the former "team and logistics" headers because we re-orged the teams slightly this year and I'm going to update that at some point too.

### CODE REVIEW

**Comment by phildini** [comment]
@williln I think it's true that I'm not a member of the org or repo.

**Comment by felipe-lee** [comment]
It's my first time helping out with a conference so seeing the timeline like this is very helpful and will be nice to have as part of the docs.

**Comment by jefftriplett** [comment]
@phildini and @felipe-lee I saw your note about not having access. You should both have invites for the 2019 team now.

**Comment by williln** [comment]
@felipe-lee @phildini Okay, I think the timeline is now ready to merge. Any final thoughts?

**Review by jefftriplett — APPROVED** [review]

**Pull request merged**
